name: Actualizar EPG

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install requests pytz
          pip install lxml pytz requests

      - name: Ejecutar script
        run: python generate_epg_html.py

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add and commit changes if any
        run: |
          git add TV.xml.gz programacion.html || echo "No new files to add"
          git commit -m "Agregar archivos EPG y la programación generada" || echo "No changes to commit"
          git push origin main
